#spring:
#  jpa:
#  database: postgresql
#  hibernate.dialect: org.hibernate.dilect.PostgreSQLDialect
#  hibernate.ddl-auto: update
#  properties.hibernate.format_sql: true
#  show-sql: true

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-214-132-149.compute-1.amazonaws.com/db73es4tnbgqmi
  username: bdvzqzcdkkvpni
  password: a5ada80c84f8e2ef6cd3e2b5df4601ac46b25414aca50a713f83ce5fab8e3f41
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  token.expired-time-ms: 2592000000